# -*- coding: utf-8 -*-
str_login = {'en':'Login', 'cn':'登录'.decode("utf-8")}
str_username = {'en':'User','cn':'用户'.decode("utf-8")}
str_pwd = {'en':'Pwd','cn':'密码'.decode("utf-8")}
str_ok = {'en':'Ok','cn':'确定'.decode("utf-8")}
str_cancel = {'en':'Cancel','cn':'取消'.decode("utf-8")}
str_failure = {'en':'Failure','cn':'失败'.decode("utf-8")}
str_success = {'en':'Success','cn':'成功'.decode("utf-8")}
str_idle = {'en':'Idle','cn':'空闲'.decode("utf-8")}
str_tws = {'en':'TWS','cn':'组队成功'.decode("utf-8")}
str_stop = {'en':'Stop','cn':'停止'.decode("utf-8")}
str_burning = {'en':'Burning','cn':'烧录中'.decode("utf-8")}
text_success_count = {'en':'Accomplish count:','cn':'完成统计:'}
text_failure_count = {'en':'Failure count:','cn':'失败统计:'}
str_progress = {'en':'Progress (%)','cn':'进度 (%)'.decode("utf-8")}
str_status = {'en':'Status','cn':'状态'.decode("utf-8")}
str_elapse = {'en':'Elapse','cn':'计时'.decode("utf-8")}
str_closed = {'en':'Closed','cn':'已关闭'.decode("utf-8")}
str_factory_mode = {'en':'Factory mode', 'cn':'工厂模式'.decode("utf-8")}
str_crc_verify_failure = {'en':'CRC Verify Failure', 'cn':'crc校验失败'.decode("utf-8")}
str_updatetool_title = {'en':'Update Tool', 'cn':'升级工具'.decode("utf-8")}
str_dldtool_title = {'en':'Productline Tool', 'cn':'产线工具'.decode("utf-8")}
str_dldtool_encrypt_title = {'en':'Productline Tool(encrypt)', 'cn':'产线工具(加密)'.decode("utf-8")}
str_testing = {'en':'Testing', 'cn':'测试中'.decode("utf-8")}
str_complete_count = {'en':'Complete Count: ', 'cn':'完成数: '}
str_failure_count = {'en':'Failure Count: ', 'cn':'失败数: '}
str_port_num = {'en':'Number', 'cn':'端口号'.decode("utf-8")}
str_calib_value = {'en':'Calib Value','cn':'校准值'.decode("utf-8")}
str_com = {'en':'COM', 'cn':'串口'.decode("utf-8")}
# str_progress = {'en':'Progress', 'cn':'进度 (%)'.decode("utf-8")}
str_bt_name = {'en': 'Bt Name: ', 'cn': '蓝牙名称: '.decode("utf-8")}
str_ble_name = {'en': 'Ble Name: ', 'cn': 'BLE名称: '.decode("utf-8")}
str_bt_addr = {'en':'Bt Addr: ', 'cn':'BT地址: '.decode("utf-8")}
str_ble_addr = {'en':'BLE Addr: ', 'cn':'BLE地址: '.decode("utf-8")}
str_bin1_path = {'en':'bin path1: ', 'cn':'bin文件路径1: '}
str_bin2_path = {'en':'bin path2: ', 'cn':'bin文件路径2: '}
str_btaddr_filter = {'en':'bt addr grow filter', 'cn':'地址过滤'.decode("utf-8")}
str_btaddr_add1 = {'en':'bt addr grow', 'cn':'地址递增'.decode("utf-8")}
str_btaddr_fixed = {'en':'bt addr fixed', 'cn':'地址固定'.decode("utf-8")}
str_btaddr_Raise_2 = {'en':'bt addr grow 2', 'cn':'地址自增2'.decode("utf-8")}
str_sn_add = {'en':'SN grow', 'cn':'SN递增'.decode("utf-8")}
str_sn_fixed = {'en':'SN fixed', 'cn':'SN固定'.decode("utf-8")}
str_key_format_not_supported = {'en':'RSA key format is not supported', 'cn':'RSA key format is not supported'}
str_burning_method = {'en':'burning method', 'cn':'烧录方法'}
str_burning_team = {'en':'TWS', 'cn':'tws组队烧录'}
str_burning_not_team = {'en':'non-TWS', 'cn':'tws不组队烧录'}